# Generated by Django 5.2.3 on 2025-06-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsafeuser',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
