# Generated by Django 5.2.3 on 2025-06-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_unsafeuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unsafeuser',
            old_name='password',
            new_name='password_hash',
        ),
    ]
