# Generated by Django 5.2.3 on 2025-06-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_unsafeuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsafeuser',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
