# Generated by Django 5.2.3 on 2025-06-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_password_unsafeuser_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsafeuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='unsafeuser',
            name='username',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
